services:
  - type: web
    name: one-in-a-million
    runtime: node
    plan: free
    buildCommand: npm run build:render
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SETUP_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: VITE_MAPTILER_API_KEY
        sync: false
      - key: MAPTILER_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        value: noreply@oneinamillion.com
      - key: BREVO_SENDER_NAME
        value: One in a Million
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        value: one-in-a-million/images
      - key: ORS_API_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false

